# Generated by Django 2.0.9 on 2024-01-18 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laundry',
            name='HOSTEL_OWNER',
        ),
        migrations.AddField(
            model_name='laundry',
            name='HOSTEL',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hostel_app.hostel'),
        ),
    ]
