# Generated by Django 2.0.9 on 2024-01-19 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_app', '0002_auto_20240118_1008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laundry',
            name='ROOM_REQUEST',
        ),
    ]
